### ISSUE TITLE
Builds are broken

### ISSUE THREAD

**Issue by LeoColomb** [mshibanami/GitHubTrendingRSS#4]
Just a little bump 'cause builds are no more running... 🙂 

https://travis-ci.org/mshibanami/GitHubTrendingRSS

![image](https://user-images.githubusercontent.com/846943/71635113-e96d0380-2c21-11ea-8e32-e852775df794.png)

**Comment by mshibanami** [comment]
Hi @LeoColomb,
Sorry for not noticing about this issue.

Nowadays GitHub Trending became bigger and it usually takes over 50 mins to fetch all feeds so Travis CI stops running this tool.
To let this tool to run faster, I'm planning to replace RxSwift, a library that takes too long to fetch/build, with Combine. However, since Combine is available on Catalina and Catalina hasn't been supported by Travis CI yet, I've been waiting for the support but it seems that we'd have to wait more... 

Anyway, I've just updated the feeds on my machine as a temporary workaround. Please try it.

For now, I'll continue providing the feeds generated by Jenkins on my machine until Travis CI supports Catalina but replacing the libraries might be not so effective so perhaps I'll try other solutions, like:

- Move to another CI service that lets us run a build it for enough time
    - Perhaps I'll need to use Linux for the build environment.
- Remove some languages from [popularLanguages](https://github.com/mshibanami/GitHubTrendingRSS/blob/ea64981/Sources/GitHubTrendingRSSKit/Const.swift#L31).
- Build feeds partially (e.g. odd days are for building weekly & daily feeds.)

**Comment by LeoColomb** [comment]
Thanks @mshibanami!

> Sorry for not noticing about this issue.

No worries, I know this kind of service can be painful to maintain.

> I'll try other solutions

Maybe all three solutions 😉 
Reducing the number of language might be the easier mitigation, I'm not sure lots of people follow almost unknown languages.

You can also split builds by language, can't you?

Anyway, thanks again!

**Comment by mshibanami** [comment]
> Reducing the number of language might be the easier mitigation, I'm not sure lots of people follow almost unknown languages.
>
> You can also split builds by language, can't you?

Both of them look pretty nice. I'll try it, thanks Léo!

I'd close this issue when I completely fixed this issue.

**Comment by LeoColomb** [comment]
They are working fine now, you've done a nice work on this.

Thanks again!

**Comment by mshibanami** [comment]
Thanks for confirming it!
